import os

def write_top_mdp_files(output_dir, residue_name):
    # --- topol.top ---
    top_path = os.path.join(output_dir, "topol.top")
    with open(top_path, "w") as f:
        f.write(
f"""; Topology generated by nsaa-paramgen
; Modify force field, solvent, or ions as needed

#include "amber99sb.ff/forcefield.itp"
#include "{residue_name}.itp"

[ system ]
{residue_name} test system

[ molecules ]
{residue_name} 1
"""
        )

    # --- em.mdp ---
    em_path = os.path.join(output_dir, "em.mdp")
    with open(em_path, "w") as f:
        f.write(
"""integrator      = steep
nsteps          = 5000
emtol           = 1000.0

cutoff-scheme   = Verlet
coulombtype     = Cut-off
rcoulomb        = 0.8
rvdw            = 0.8

constraints     = h-bonds
"""
        )

    # --- md.mdp ---
    md_path = os.path.join(output_dir, "md.mdp")
    with open(md_path, "w") as f:
        f.write(
"""integrator      = md
dt              = 0.002
nsteps          = 50000

cutoff-scheme   = Verlet
coulombtype     = PME
rcoulomb        = 1.2
rvdw            = 1.2

constraints     = h-bonds
constraint-algorithm = lincs

tcoupl          = V-rescale
tc-grps         = System
tau_t           = 0.1
ref_t           = 300

pcoupl          = no
"""
        )

    print("Generated topol.top, em.mdp, md.mdp")
